<<<<<<< HEAD
=======
image: gitlab/dind

services:
  - docker:dind

>>>>>>> 3a0023d4ca1a072ceff57a3afee9424dfdcad4a8
stages:
  - build
  - test
  - deploy

sast:
  stage: build
  script:
   - docker pull secfigo/bandit
   - docker run --user $(id -u):$(id -g) -v $(pwd):/src --rm secfigo/bandit bandit -r /src
  allow_failure: true
<<<<<<< HEAD

=======
>>>>>>> 3a0023d4ca1a072ceff57a3afee9424dfdcad4a8
